repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    - id: no-commit-to-branch
      args: ["--branch", "main"]
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: detect-private-key
    - id: mixed-line-ending
    - id: check-case-conflict

-   repo: https://github.com/pycqa/isort
    rev: 5.9.3
    hooks:
    - id: isort
      args: ["--profile", "black", "--filter-files"]

-   repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
    - id: black
      args: [--line-length=120, --exclude="""\.git|.__pycache__|\.venv"""]
      #language_version: python3.7

-   repo: https://github.com/pycqa/flake8
    rev: 3.7.9
    hooks:
    - id: flake8
      args: ['--ignore=E501, D100, D101, D102, D103, D104, D105, D106, D107, F811, E713, E203, W503']
